version: '3'
services:
  frontapp:
    image: yasminelakhdher/user_app:frontapp-${env.BUILD_NUMBER}
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
