version: '3'
services:
  npm-install:
    image: node:14
    volumes:
      - ./angular-app:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install"

  frontapp:
    image: yasminelakhdher/user_app:frontapp-1
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./angular-app:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
